<a href="https://colab.research.google.com/github/ArunNiranjan/tensorflowtutes/blob/main/Tensorflow_Funadamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf

In [3]:
print(tf.__version__)

2.8.2


In [4]:
tf1 = tf.constant([1,2,3,4])

In [5]:
tf1

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [6]:
tf2 = tf.Variable([5,6,7,8])

In [7]:
tf2

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([5, 6, 7, 8], dtype=int32)>

In [8]:
tf2[0].assign(10)

<tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([10,  6,  7,  8], dtype=int32)>

In [9]:
tf2

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([10,  6,  7,  8], dtype=int32)>

In [10]:
# tf1[0].assign(11)
#we cant assign values to unchangeble tensor

In [11]:
tf3 = tf.constant([[1,2],[3,4]])
tf3


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [12]:
tf4 = tf.constant([[[1,2,3],[4,5,6]],[[8,9,10],[11,12,13]]])
tf4

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 8,  9, 10],
        [11, 12, 13]]], dtype=int32)>

In [13]:
print('Number of dimension', tf4.ndim)
print('Shape of matrix',tf4.shape)
print('number of elements', tf.size(tf4))

Number of dimension 3
Shape of matrix (2, 2, 3)
number of elements tf.Tensor(12, shape=(), dtype=int32)


In [14]:
tf4.shape[0]

2

In [15]:
tf4.shape[-1]

3

In [16]:
tf4[:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 4,  5]],

       [[ 8,  9],
        [11, 12]]], dtype=int32)>

In [17]:
tf4[:1,:2,:2]

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [4, 5]]], dtype=int32)>

In [18]:
import numpy as np

In [19]:
num_array = np.arange(1,20, dtype= int)
num_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [20]:
tf_new = tf.constant(num_array)

In [21]:
tf_new

<tf.Tensor: shape=(19,), dtype=int64, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])>

In [22]:
tf5 = tf.random.Generator.from_seed(15)
tf5 = tf5.normal(shape = (3,3))
tf5

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.33149973, -0.5445254 ,  1.5222508 ],
       [ 0.59303206, -0.63509274,  0.3703566 ],
       [-1.0939722 , -0.4601445 ,  1.5420506 ]], dtype=float32)>

In [23]:
tf.random.set_seed(43)
tf.random.shuffle(tf5, seed = 43)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.33149973, -0.5445254 ,  1.5222508 ],
       [-1.0939722 , -0.4601445 ,  1.5420506 ],
       [ 0.59303206, -0.63509274,  0.3703566 ]], dtype=float32)>

In [24]:
tf6 = tf.constant([[1,2,3],[4,5,6]])
tf7 = tf.constant([[5,6],[7,8],[9,10]])
tf6, tf7

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 5,  6],
        [ 7,  8],
        [ 9, 10]], dtype=int32)>)

In [25]:
tf.matmul(tf6,tf7)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 46,  52],
       [109, 124]], dtype=int32)>

In [26]:
## We need to use tf.transpose to Transpose the matrix, if the mutrix shape is inconvienet for matrix multiplication

In [27]:
tf.transpose(tf7)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 5,  7,  9],
       [ 6,  8, 10]], dtype=int32)>

In [28]:
tf.reshape(tf7, shape = (2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 5,  6,  7],
       [ 8,  9, 10]], dtype=int32)>

In [29]:
# There is different value when we tried with reshape method so need to use tf.transpose method

In [30]:
tf8 = tf.constant([3.2, 4.5, 7.7])

In [31]:
tf8

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([3.2, 4.5, 7.7], dtype=float32)>

In [32]:
tf.cast(tf8, dtype = np.float16)

<tf.Tensor: shape=(3,), dtype=float16, numpy=array([3.2, 4.5, 7.7], dtype=float16)>

In [33]:
#Aggregation functions

In [34]:
tf9 = tf.constant(np.random.randint(0,100, size = 50))

In [35]:
tf9

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([69, 14, 98, 64, 50, 65, 46, 28, 56,  7, 41, 74, 36, 78,  9, 91, 68,
       80, 31,  7, 42, 84, 59,  5, 41, 17, 65, 71, 15, 30, 18,  8, 27, 69,
       12, 75, 94, 53, 16, 92, 28, 61, 70,  2, 36, 42, 58, 26, 39, 78])>

In [36]:
tf9.ndim, tf9.shape, tf.size(tf9)

(1, TensorShape([50]), <tf.Tensor: shape=(), dtype=int32, numpy=50>)

In [37]:
tf.reduce_min(tf9)

<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [38]:
tf.reduce_max(tf9)

<tf.Tensor: shape=(), dtype=int64, numpy=98>

In [39]:
tf.reduce_mean(tf9)

<tf.Tensor: shape=(), dtype=int64, numpy=46>

In [40]:
tf.reduce_sum(tf9)

<tf.Tensor: shape=(), dtype=int64, numpy=2345>

In [41]:
tf.math.reduce_std(tf.cast(tf9, dtype = float))

<tf.Tensor: shape=(), dtype=float32, numpy=27.288277>

In [42]:
tf.math.reduce_variance(tf.cast(tf9, dtype = float))

<tf.Tensor: shape=(), dtype=float32, numpy=744.6501>

In [43]:
# Find positional min and max

In [1]:
## Tensorflow Fundamentals Exercise

In [44]:
tf_1 = tf.constant([1,2,3])

In [45]:
tf_2 = tf.constant([[1,2,3],[4,5,6]])

In [52]:
tf_2.shape, tf_2.ndim, tf.size(tf_2)

(TensorShape([2, 3]), 2, <tf.Tensor: shape=(), dtype=int32, numpy=6>)

In [54]:
tf_3 = tf.random.Generator.from_seed(42)
tf_3 = tf_3.normal(shape = (5,300))

In [56]:
tf_4 = tf.random.Generator.from_seed(38)
tf_4 = tf_4.normal(shape = (5,300))

In [55]:
tf_3

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026, ..., -1.071834  ,
        -1.0722276 , -0.00586287],
       [-0.88051033, -0.32426047, -2.4847078 , ...,  0.16512105,
         1.155565  , -0.10707551],
       [-1.5306779 , -0.86202925, -0.16359143, ...,  0.34288085,
         1.216793  , -1.24293   ],
       [ 0.84324265, -0.23379943,  0.4276398 , ..., -1.0428714 ,
        -0.73970354,  0.0177109 ],
       [ 0.04888754, -0.66408694, -1.787366  , ...,  0.1947453 ,
         0.5656089 ,  0.18439196]], dtype=float32)>

In [59]:
tf_4_transposed = tf.transpose(tf_4)

In [61]:
tf_3.shape, tf_4_transposed.shape

(TensorShape([5, 300]), TensorShape([300, 5]))

In [62]:
tf.matmul(tf_3, tf_4_transposed)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ -7.0561275,  24.473665 , -35.8183   , -17.41225  , -12.622992 ],
       [ -9.957701 , -28.559114 ,  39.03465  , -19.910313 , -23.325115 ],
       [ -5.0240793,  40.843716 , -28.540802 ,  -6.970851 ,  23.484581 ],
       [  7.267663 ,  18.51926  ,  -8.787794 ,  16.000908 ,  -5.6527424],
       [ 17.789812 ,  19.030727 ,   5.5636053,  31.378265 ,  12.695045 ]],
      dtype=float32)>

In [63]:
tf_5 = tf.random.Generator.from_seed(42)
tf_5 = tf_5.normal(shape = (224,224,3))

In [66]:
tf.reduce_min(tf_5)

<tf.Tensor: shape=(), dtype=float32, numpy=-4.848316>

In [68]:
tf.reduce_max(tf_5), tf.reduce_mean(tf_5)

(<tf.Tensor: shape=(), dtype=float32, numpy=4.4032865>,
 <tf.Tensor: shape=(), dtype=float32, numpy=-0.0044118334>)

In [70]:
tf_6 = tf.random.Generator.from_seed(42)
tf_6 = tf_6.normal(shape = (1,1,4,3))

In [72]:
tf_new = tf.squeeze(tf_6)

In [73]:
tf_new

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026],
       [-1.2573844 , -0.23193763, -1.8107855 ],
       [ 0.09988727, -0.50998646, -0.7535805 ],
       [-0.57166284,  0.1480774 , -0.23362993]], dtype=float32)>

In [79]:
tf.math.argmax(tf_new,1)

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([2, 1, 0, 1])>